In [68]:
import os, csv
import pandas as pd

os.getcwd()

'/Users/caoziyi/Desktop/第三篇/MLLM-MSR-main/MLLM-MSR/data/microlens/preprocessing'

In [69]:
df = pd.read_csv('../../MicroLens-50k_pairs.csv')
print(f'shape: {df.shape}')
df[:5]
print(df['item'].nunique())

shape: (359708, 3)
19220

In [73]:
from collections import Counter
import numpy as np

min_u_num, min_i_num = 7, 5

def get_illegal_ids_by_inter_num(df, field, max_num=None, min_num=None):
    if field is None:
        return set()
    if max_num is None and min_num is None:
        return set()

    max_num = max_num or np.inf
    min_num = min_num or -1

    ids = df[field].values
    inter_num = Counter(ids)
    ids = {id_ for id_ in inter_num if inter_num[id_] < min_num or inter_num[id_] > max_num}
    print(f'{len(ids)} illegal_ids_by_inter_num, field={field}')

    return ids


def filter_by_k_core(df):
    while True:
        ban_users = get_illegal_ids_by_inter_num(df, field='user', max_num=None, min_num=min_u_num)
        ban_items = get_illegal_ids_by_inter_num(df, field='item', max_num=None, min_num=min_i_num)
        if len(ban_users) == 0 and len(ban_items) == 0:
            return

        dropped_inter = pd.Series(False, index=df.index)
        if 'user':
            dropped_inter |= df['user'].isin(ban_users)
        if 'item':
            dropped_inter |= df['item'].isin(ban_items)
        print(f'{len(dropped_inter)} dropped interactions')
        df.drop(df.index[dropped_inter], inplace=True)

In [74]:
filter_by_k_core(df)
print(f'k-core shape: {df.shape}')
print(f'shape after k-core: {df.shape}')
df[:5]

0 illegal_ids_by_inter_num, field=user
0 illegal_ids_by_inter_num, field=item
k-core shape: (145835, 3)
shape after k-core: (145835, 3)

    user  item      timestamp
0  36121  9580  1583378629552
2  37550  9580  1584412681021
3  14601  9580  1584848802432
4  15061  9580  1585388171106
6   3542  9580  1585404918503

In [75]:
print(df['user'].nunique())
print(df['item'].nunique())

14323
9535

In [76]:
import pandas as pd
import numpy as np

# df has three columns: 'user', 'item', 'timestamp'

# calculate the frequency of each item
item_frequency = df.groupby('item').size().reset_index(name='frequency')

# sort items by frequency in descending order
item_frequency_sorted = item_frequency.sort_values(by='frequency', ascending=False)

# sort the original dataframe by timestamp
df_sorted = df.sort_values('timestamp')

# get all unique items and users
all_items = set(df_sorted['item'].unique())
all_users = df_sorted['user'].unique()

# generate negative samples for each user
negative_samples_per_user = {}
for user in all_users:
    user_items = df_sorted[df_sorted['user'] == user]['item'].unique()
    available_items = list(all_items - set(user_items))
    negative_samples = np.random.choice(available_items, size=min(20, len(available_items)), replace=False)
    negative_samples_per_user[user] = negative_samples

print(len(negative_samples_per_user.keys()))

14323

In [21]:
top_6_items_per_user = {}
for user in all_users:
    # get the items interacted by the user
    user_items = df_sorted[df_sorted['user'] == user]['item']
    # get the top 6 items based on frequency
    top_6_items = user_items.map(item_frequency_sorted.set_index('item')['frequency']).sort_values(ascending=False).index[:6]
    # sorted these top 6 items by timestamp
    top_6_items_per_user[user] = df_sorted.loc[top_6_items].sort_value('timestamp')['item'].values

AttributeError: 'DataFrame' object has no attribute 'sort_value'

In [34]:
user = all_users[0]
user_items = df_sorted[df_sorted['user'] == user]['item']
top_6_items = (
        user_items
        .map(item_frequency_sorted.set_index('item')['frequency'])
        .sort_values(ascending=False)
        .index[:6]
    )
top_6_items_per_user[user] = df_sorted.loc[top_6_items].sort_values('timestamp')['item'].values


top_6_items_per_user[user]

array([16845, 15199,  9350, 17437, 12846,   675])

In [35]:
top_6_items_per_user = {}
for user in all_users:
    # 用户交互过的 items
    user_items = df_sorted[df_sorted['user'] == user]['item']

    # 找到这用户 top-6 高频 items
    top_6_items = (
        user_items
        .map(item_frequency_sorted.set_index('item')['frequency'])
        .sort_values(ascending=False)
        .index[:]
    )

    # 按 timestamp 排序
    top_6_items_per_user[user] = df_sorted.loc[top_6_items].sort_values('timestamp')['item'].values
top_6_items_per_user

{np.int64(36121): array([16845, 15199,  9350, 17437, 12846,   675]),
 np.int64(37550): array([16221,  8715,  8964,  2247, 19572, 14190]),
 np.int64(14601): array([14083, 12203, 18435,  7712,  4896, 18225]),
 np.int64(15061): array([ 7990, 12687, 13681, 19282, 10602, 10694]),
 np.int64(3542): array([ 3159, 18893,  6715, 19315,  9538, 16128]),
 np.int64(47592): array([14631,  9647, 17091,  3558, 12699, 17993]),
 np.int64(26119): array([14631, 15968,  2837,  7408,  8051, 19080]),
 np.int64(31970): array([ 7920,  5922, 13591, 17436,  6911,  3870]),
 np.int64(47771): array([14631, 19198,  4223,  3368, 15623, 13996]),
 np.int64(11254): array([14631, 15983, 14884, 16729, 17974,  8093]),
 np.int64(25902): array([ 7315, 15591, 14860,  6398, 16301, 17302]),
 np.int64(48195): array([14631, 17099,  7043, 12645,  3870,  7233]),
 np.int64(9851): array([ 7315, 15742,  5525,  6783,  8160, 15841]),
 np.int64(28036): array([14631,  7315,  1638, 11984,  2308,  7207]),
 np.int64(16718): array([14631,  2167,  7753,  3521, 18910, 13605]),
 np.int64(14633): array([14631, 14196, 16539, 11605,  9439, 18097]),
 np.int64(16055): array([ 7315, 15430,  8892,   784,  4943, 19169]),
 np.int64(31698): array([14631, 17558, 13249,  6484,  9830,  5355]),
 np.int64(11022): array([16573,  6875,  2672, 11642, 15253,  4208]),
 np.int64(46458): array([ 3591, 16419, 11199,  1653,  1522, 12364]),
 np.int64(19956): array([12983, 19080, 17692,  5681, 10437,  7593]),
 np.int64(18808): array([ 9181, 18897, 16886, 13296, 16944,  6233]),
 np.int64(43385): array([19680, 12383,  3510, 11343,  1646, 11915]),
 np.int64(37695): array([18387,   195,  8547, 12663,   202, 16488]),
 np.int64(26227): array([12331, 13656,  2316,  8538, 16673,  6513]),
 np.int64(28924): array([14876, 19314, 19680,    24,  1986,   947]),
 np.int64(10910): array([14631,  7736,   709, 19135,  3978,  6051]),
 np.int64(42757): array([ 5600,  5500,  4801, 15200, 14089,  6039]),
 np.int64(22367): array([ 6266,  7764,  4273, 11190,  8448, 12745]),
 np.int64(47657): array([ 1085, 10524, 10753, 16477,  7704, 10383]),
 np.int64(36070): array([12077, 13160,  2449, 19560, 18525, 17474]),
 np.int64(5510): array([12077,   621, 10672,   195, 14896,  6481]),
 np.int64(35105): array([17887,  1882,  7379, 17474, 14387,  6051]),
 np.int64(1309): array([12077,  5509, 10663,   740, 13683, 17474]),
 np.int64(20702): array([14631,   190,  3209, 12387,  6240, 16577]),
 np.int64(16110): array([ 3533,  2820, 12878,  5922, 10239, 18260]),
 np.int64(7958): array([ 3104, 13569, 12352,  8907, 12532,   776]),
 np.int64(25776): array([ 7315, 12077,  1409, 16026, 19314,  1085]),
 np.int64(45125): array([16944,  6875, 15312,  1921,  3612, 16077]),
 np.int64(19471): array([14568, 10524, 19080,   553,  6646,   346]),
 np.int64(16576): array([ 1955,  8803, 10115,  3922,  1926, 15040]),
 np.int64(23931): array([ 7568,  4105, 10866, 15628, 12305, 18225]),
 np.int64(28759): array([ 9799,  3052,  4782, 18260, 18001, 17047]),
 np.int64(30992): array([16573,  4501,  9497, 14116, 11605, 11811]),
 np.int64(21308): array([12077,  8623,  4726,  5601, 13844,  1186]),
 np.int64(27620): array([11449,  1178,  9233, 18480, 14433, 14928]),
 np.int64(25342): array([19567, 10024,  9477,  2281, 13361, 10637]),
 np.int64(9328): array([16419, 18813, 10242,  5475, 12434,  7381]),
 np.int64(20625): array([ 7771,  3960,  8163, 17974,  1441,  4657]),
 np.int64(13728): array([  195,  2672,  7920, 11379,  4455, 10437]),
 np.int64(24512): array([ 5390, 13210,  1340,  8765,  5475, 14484]),
 np.int64(9221): array([ 2237, 13243,  5539,  1217, 17969, 16153]),
 np.int64(23611): array([ 2993,  8661,  7790, 12671, 14530,  9938]),
 np.int64(29451): array([10438, 16196, 14151,  2718, 19386,  1782]),
 np.int64(11853): array([16425,  5434,  2567, 16128, 13871,  3348]),
 np.int64(36296): array([16425, 11203,  9830,  3667, 14230, 14959]),
 np.int64(45335): array([16425, 14009, 10320, 10239,   311,  3612]),
 np.int64(43060): array([16425,  3137, 12766, 10322, 15026, 17837]),
 np.int64(26682): array([ 3667, 17354, 13627, 16766, 18724, 19537]),
 np.int64(10710): array([16425,  3213, 19576,  2602, 18186,  2469]),
 np.int64(26219): array([16425, 10682, 11868,  5430, 15606,  7910]),
 np.int64(27487): array([16425,  4266, 19401,   623,  6035,  9659]),
 np.int64(8369): array([11842, 19159,  7487, 19564, 13683, 19269]),
 np.int64(17984): array([16425,  3445,  6213, 19305,  3854,    75]),
 np.int64(39284): array([16425,  5091, 11609, 17141, 19633, 15502]),
 np.int64(47305): array([11733, 14993,  5790,  1638,  3445, 15914]),
 np.int64(41303): array([16425, 11236, 18251,  2761,  8104,  8371]),
 np.int64(23639): array([16425, 17258, 13254, 10851,   123, 14683]),
 np.int64(31763): array([16425, 10119, 18083, 19153,  6389, 11888]),
 np.int64(19195): array([16425, 16573, 10524, 14387,  1333,  1689]),
 np.int64(25117): array([16221,  5713,  9519,   346,  8784,  1599]),
 np.int64(4544): array([16425, 19314,   311, 17581, 16207, 16462]),
 np.int64(25572): array([2550, 3209, 4737, 7860, 1600, 8780]),
 np.int64(45172): array([ 1148, 11133,  5129,  2492, 17636, 19305]),
 np.int64(23963): array([16573,  5355, 13569, 16746,  7558, 15091]),
 np.int64(98): array([11111, 13072,  6470,  5355,  8996, 13193]),
 np.int64(1733): array([13546,  3265, 10018,  6446, 15763, 10932]),
 np.int64(37859): array([  621, 11199, 11800, 14334,  9809, 17959]),
 np.int64(43002): array([ 6898,  4744,  8860,  2702,  5935, 13487]),
 np.int64(9978): array([ 3591,  4216,  4926, 18285, 16677,  3214]),
 np.int64(11239): array([ 8387,  3291, 13175, 18366,  2643,  4071]),
 np.int64(27683): array([ 2468,  6413, 19661,  5712,  3571,  6826]),
 np.int64(48320): array([ 6875, 12352, 11984, 17534, 13447,  3612]),
 np.int64(10152): array([ 2846, 17351,  1987,  3769,  8996,  1689]),
 np.int64(21828): array([ 2761,  4338, 12133,   776, 13605, 11498]),
 np.int64(12404): array([17532, 16095, 18011,  5808, 18497,  3241]),
 np.int64(376): array([ 3137, 18980,  8355, 13844,  5719,  3949]),
 np.int64(21854): array([19314,  3325,  9477,  8721, 10921,   950]),
 np.int64(4117): array([  621, 16245,  3128, 14045,  6581, 11929]),
 np.int64(10409): array([  621, 13481, 10515, 16245, 12945,  9203]),
 np.int64(28066): array([  621, 15287, 16756,  9953, 11820, 15955]),
 np.int64(25188): array([ 5790,   981, 16573,  1349,  4328, 18781]),
 np.int64(12971): array([ 8249, 12945, 16886, 16944, 15775, 17456]),
 np.int64(45996): array([  621, 15135, 18864, 17096,  7917, 14498]),
 np.int64(38220): array([  621,  2837, 13569, 18525,  7604,  2567]),
 np.int64(18423): array([  621, 16756,  9354, 14455, 13210, 14197]),
 np.int64(969): array([10223, 16049,  9307, 19094,  1754, 16936]),
 np.int64(29249): array([  621,    44, 14507,    24,  8068,  7996]),
 np.int64(15654): array([ 4208, 15049,  1714,  9497, 14091,  5345]),
 np.int64(4658): array([16420, 10437, 16285, 11343,  7632,  3870]),
 np.int64(19707): array([  621, 17887,  5355, 17182, 10753, 10663]),
 np.int64(35175): array([ 9307, 14367, 18891,  2038,   682, 11172]),
 np.int64(10175): array([ 3805,  3001, 14021,  8118,  7369,    43]),
 np.int64(23985): array([14229, 13598,   966,  1796, 19051,  2141]),
 np.int64(5517): array([  189, 15192,   469, 14770,  4990, 17072]),
 np.int64(14853): array([15775, 18361, 16981,  6539, 13568,  1846]),
 np.int64(49939): array([  621, 11182,  3680, 13824, 11726, 16462]),
 np.int64(46199): array([ 658, 5541, 8637, 4782, 5169, 2341]),
 np.int64(3065): array([  621, 10474, 12312, 15124,  1361,  6713]),
 np.int64(25673): array([14496,  5355, 10487, 12766,  2259,  1349]),
 np.int64(35213): array([18827, 17875,  9251,  4611,   888, 15702]),
 np.int64(46794): array([  621,  3065, 19170, 18387,  3298, 13584]),
 np.int64(4394): array([ 7670,  8051,  3092, 13296,  3329,  2602]),
 np.int64(19452): array([19658, 11295,  8855, 17217, 12468,  7352]),
 np.int64(35953): array([ 6668,  3577, 13787,  4929, 13884, 15098]),
 np.int64(12970): array([11884, 17442, 19258, 12706,  3343,  3259]),
 np.int64(11401): array([12983,   735, 18813,  8710, 16428,  2967]),
 np.int64(3970): array([ 5436, 19112, 13384, 12374, 11437, 15955]),
 np.int64(26755): array([10589, 16274,  1410,  6529,  3269, 19307]),
 np.int64(2103): array([10223,    93,  6736,  6036,  1277, 12802]),
 np.int64(21608): array([14283, 19385,  1203, 19094, 14257,   855]),
 np.int64(24730): array([17812, 16719, 10715,  6657,  4580,  4988]),
 np.int64(20832): array([  858, 18782,  8637,  3554, 10412,  6814]),
 np.int64(15356): array([15591, 14186,  2854, 19264,  7105,  8418]),
 np.int64(12396): array([10954, 13753,   450,  7631,  7434, 19274]),
 np.int64(4039): array([ 9973,  3228, 19430,  3725, 12315,  5421]),
 np.int64(22408): array([16942, 17731,  3807, 12715, 15816,  9564]),
 np.int64(23975): array([14186,  6084, 14091,   947,  3104, 12150]),
 np.int64(44865): array([ 6896,  8442, 16301, 19305,   911, 15955]),
 np.int64(44206): array([15262, 18215,  8624,  7149,  6183,  6036]),
 np.int64(49392): array([13788, 13122,  7016,  8453,  5293,  6554]),
 np.int64(30786): array([13610, 10031, 14951,  9203,  1005,   254]),
 np.int64(27875): array([ 6398, 10157, 18832, 17731, 11063, 15816]),
 np.int64(34911): array([18862,  3310, 16313,  3631,  3998,  7079]),
 np.int64(37012): array([  917,  2360,  8247, 16477,  3495,  6743]),
 np.int64(12107): array([  917, 16510, 13243, 12448,  2360, 11372]),
 np.int64(30306): array([  917,  8247,   476, 14324,  7576, 16675]),
 np.int64(11856): array([18504,   917,  8247, 16477,  3495,  6743]),
 np.int64(677): array([16425,  7261,  2757,  8855, 17490, 13704]),
 np.int64(43115): array([19385,   151, 17824,  6557, 16759,  3854]),
 np.int64(15858): array([ 7771,  6668,  1277,  5424, 18096,  3929]),
 np.int64(14196): array([15194,  5926,  8643,  9364, 11325,   870]),
 np.int64(10510): array([ 2550,  4682, 16147, 11754,  5543,  2389]),
 np.int64(29825): array([18072, 11111, 17258,  2846, 13594,  7029]),
 np.int64(1027): array([ 1511,  8516,  7583, 12196, 11285,  4365]),
 np.int64(17534): array([14865,   412,  3106,  1815, 15163, 11498]),
 np.int64(44415): array([12980,  6072,    68,   223, 16798, 15279]),
 np.int64(49192): array([18257,  3058,  4100, 17222, 19131,  2744]),
 np.int64(15827): array([ 9783,  1724, 13076,  8649,   947,  2884]),
 np.int64(29077): array([ 2360,  8247, 18504, 16477,  3495,  6743]),
 np.int64(15542): array([11372, 14891, 17269,  4435, 14559,  9816]),
 np.int64(18857): array([18504,  2237,  2360,  4037,  8247, 16477]),
 np.int64(4475): array([18032, 10524,  4501, 11063,  8070,  6979]),
 np.int64(49098): array([16425,  6398, 15435, 17022, 13526, 10323]),
 np.int64(5737): array([ 2550, 11839,  5759,  3947, 10144,  3966]),
 np.int64(19401): array([14805, 13983,  9408, 11719,  5619, 15931]),
 np.int64(47601): array([17398, 17757,  2311,   500,  1664, 14140]),
 np.int64(17296): array([11278, 16673, 17047,  1111, 12678, 16280]),
 np.int64(18980): array([19680, 16301,  9203, 11059, 11866,  7437]),
 np.int64(30117): array([17945, 11392, 17664,  1782,  6126,  7383]),
 np.int64(13720): array([ 1281, 19629,  2001,  7630,   232,  1814]),
 np.int64(6049): array([18584,  9983,  7630,  3205, 16388, 18303]),
 np.int64(9559): array([19277, 12798, 17898, 16388, 10778, 15842]),
 np.int64(18719): array([19277,  5031, 15563,  6711, 13321, 10778]),
 np.int64(7449): array([14173, 16378,     2,  3205, 12896, 14049]),
 np.int64(29375): array([ 9949,  4776,  2298, 15292, 10813,  3705]),
 np.int64(9773): array([ 3058,  5734, 14610,  3291, 16417, 18820]),
 np.int64(49834): array([12164, 15109, 15417, 13714,  6035, 19206]),
 np.int64(12310): array([ 9949, 11892,  4902,  7343,  1626, 19469]),
 np.int64(5997): array([12164,  5758,  2671,  8067,  1982,  3870]),
 np.int64(33237): array([10474,  5355, 15784,  7575,   947, 13829]),
 np.int64(24302): array([ 3209,  4415, 12473,  6980, 16624, 12454]),
 np.int64(487): array([ 6711, 17898, 10778, 15842,  6837, 11631]),
 np.int64(12834): array([ 9949,  2496,  8070, 10248,   372,  5131]),
 np.int64(23229): array([ 2846,  6821,  1592,  2363,  7434, 16780]),
 np.int64(13766): array([15983, 16412,  2383, 15328, 18680,  6741]),
 np.int64(11452): array([12164, 11647, 17650,  1258,   120, 15860]),
 np.int64(30567): array([12164, 10770, 17965, 12824, 10908, 11471]),
 np.int64(49545): array([ 8116,   202, 15362,  3877,  3044, 16780]),
 np.int64(18946): array([12164,   684,  9181, 13501, 10013, 17322]),
 np.int64(12592): array([13569, 18830,  1671,   146, 18227,  2565]),
 np.int64(22342): array([15628,  4334,  2531,  4342,  1249, 11894]),
 np.int64(13660): array([12164,  6021,  2663,  9486, 14808, 13342]),
 np.int64(25679): array([ 5926,  8859,  6072, 15022, 17321, 15104]),
 np.int64(17952): array([13539,  5603, 10955,  2759,  8820,  3786]),
 np.int64(2046): array([ 9506, 15782,  3310, 10955, 15207, 18654]),
 np.int64(18594): array([13539,  9768, 16334, 14613, 16313,  3998]),
 np.int64(2858): array([16202,  3522, 13551, 12896,  2235,  2320]),
 np.int64(24189): array([ 4735,  7447,  4692,  6266,  2176, 17060]),
 np.int64(41661): array([ 4735, 14337,  8289,  5351,  5146,  3928]),
 np.int64(2796): array([19658, 19135,  3137,  6077,  9910,  1728]),
 np.int64(37816): array([ 4735, 19366, 17412, 16477, 11925, 11430]),
 np.int64(20948): array([12383,  6516,  3677, 13008, 13849, 13012]),
 np.int64(5708): array([18862, 12335, 10162, 12309, 15207,  9985]),
 np.int64(26891): array([12335, 16334, 10162, 16313,  2320,  3998]),
 np.int64(7543): array([ 9590,  5105, 19156, 19128, 15544,   585]),
 np.int64(14595): array([13539,  5396, 16510, 14881,  8247,  4115]),
 np.int64(22145): array([ 9590, 11466, 13549,  2631,  9780, 12133]),
 np.int64(47804): array([ 5355,  2987, 13123, 19142, 15651, 13487]),
 np.int64(25583): array([18630, 13241,   730, 15417,   451,  4366]),
 np.int64(30156): array([10157,   174, 11696, 15219,  2064,  1361]),
 np.int64(25544): array([15932,  4792, 18105, 14885,  7570, 13012]),
 np.int64(35926): array([16573, 17401,   178,  5543, 13206, 10949]),
 np.int64(37985): array([18387,  3209,  8695, 10437,   189, 17875]),
 np.int64(9652): array([ 9590,  8268,  3625, 11063,  6812, 12924]),
 np.int64(1503): array([16166,  2406, 11806, 14613, 12709,  7791]),
 np.int64(37160): array([ 3488, 11859,  8056,  5979, 19156, 17511]),
 np.int64(5459): array([ 9919, 16988,  4378, 17558, 18714,  8686]),
 np.int64(23088): array([11685, 15693,   780,  1230, 11806, 12299]),
 np.int64(40189): array([ 9249, 12174,  8446,  8996, 12492, 18337]),
 np.int64(36828): array([ 3970, 14177, 15189, 14023,  6126,  7383]),
 np.int64(6692): array([13481,  3558, 15927,  1911,  7551,   717]),
 np.int64(4359): array([14177,  8378, 10193, 11806,  7314,  5324]),
 np.int64(2467): array([11449, 11173, 12653,  2038,  1483,  3621]),
 np.int64(11729): array([14040, 13199, 17488,  1060, 10926, 16385]),
 np.int64(1329): array([  873,  1921, 16537, 18361,  6539,  3260]),
 np.int64(25447): array([11097, 15312, 16981,  3260,  6539,  9512]),
 np.int64(37281): array([15253,  7586, 15775, 18361, 16537, 16981]),
 np.int64(14663): array([10635, 10322, 14484, 17816, 12014,   989]),
 np.int64(42969): array([16573,   531, 10524, 17417,  6646,  1522]),
 np.int64(43702): array([12653,  7604,  8070,  2038, 14843,  2458]),
 np.int64(44377): array([ 3985, 15312,   950,  7607,  5962, 11437]),
 np.int64(46378): array([13123, 19680, 12599,  1754,  2631, 19324]),
 np.int64(44792): array([13760,  2341,  5714, 17474, 16417, 10813]),
 np.int64(21022): array([19216, 18020, 14834,  3184,   534, 18043]),
 np.int64(28300): array([ 3065,  1918, 17887, 19170,  7810, 17441]),
 np.int64(16670): array([ 6875,   873,  8710,  9910, 17959, 11437]),
 np.int64(26285): array([16185,  9047,  1561,  2946, 12369, 10199]),
 np.int64(40638): array([17558, 18714, 16539, 11316, 16420, 12364]),
 np.int64(4860): array([ 8695,  5448, 10682, 12400,   368,  4208]),
 np.int64(37500): array([15575,  1922, 18714, 13249, 13010, 19082]),
 np.int64(25486): array([ 7285,  8541, 19632,  5200, 17321, 14552]),
 np.int64(7420): array([ 9506, 14881, 18590,  3310, 16334, 14497]),
 np.int64(40908): array([13481, 17442, 18468,  7793,  1928,  6528]),
 np.int64(22749): array([ 9590,   531,   553,   795, 13230, 13210]),
 np.int64(2573): array([ 6513, 15882, 16683, 18238, 14564, 11175]),
 np.int64(6946): array([ 7123, 14634,   756,  9435,  6968, 15127]),
 np.int64(16404): array([11696,  1545,  8394,  5944, 13637,  5885]),
 np.int64(10040): array([ 3520, 13989,  2538, 16378,  3205,  3932]),
 np.int64(19289): array([16803, 16510, 13243,  4645,  8859,  9898]),
 np.int64(3317): array([ 2424, 13243,  4645, 18899, 13104,  2862]),
 np.int64(25555): array([ 8412, 13983, 13714, 14951,  8519,  5802]),
 np.int64(5890): array([ 8412,  8695,  2025,  6077,  5131, 14659]),
 np.int64(34582): array([14173,  4718,     2,  3205, 12896, 14049]),
 np.int64(34239): array([ 4780, 18255, 10611,  5409,  7540, 15663]),
 np.int64(456): array([ 3520, 15836,  3932,  3205,  8790,     2]),
 np.int64(17537): array([ 6957,  9327, 13989, 12896, 18303, 14049]),
 np.int64(5233): array([10514,  7851,  8901, 18020,  1482, 14124]),
 np.int64(40038): array([14993,  6234,  2535,  4744,  5629,  5789]),
 np.int64(49599): array([ 3520,  3932,     2,  3205,  8790, 12896]),
 np.int64(577): array([ 6875, 12945, 10084,    57, 14536,  8484]),
 np.int64(13986): array([11095,  1031,  7483,  2496, 17532, 17310]),
 np.int64(3439): array([18647,  9647,   823, 16761,  3601, 13929]),
 np.int64(38370): array([13481, 11203, 10618, 13286,  7381, 13842]),
 np.int64(49755): array([12983, 10753,  2192,  8596, 10437, 13440]),
 np.int64(8246): array([ 9590,  6655,  3351,  9356,  4437, 17059]),
 np.int64(31207): array([ 6957,  9506,  4281,  4718,  5324, 16313]),
 np.int64(129): array([ 7362,    44, 11203, 12324, 11423, 11003]),
 np.int64(25197): array([  917,   279,  8247, 19139,  3495,  6679]),
 np.int64(11459): array([18257,  7450,  8639,   340, 12859,  4474]),
 np.int64(30107): array([ 6644, 16539,  1522, 10663, 11269,  6513]),
 np.int64(44490): array([14173,  5445,  3932,     2,  8790, 12896]),
 np.int64(26010): array([ 3159, 11632,  8009, 11192, 11918, 16541]),
 np.int64(885): array([16744,  4775,  2629,  3725,  5432,   637]),
 np.int64(46573): array([ 7362, 11842, 12302,  3325, 11209, 13704]),
 np.int64(37828): array([14056,   316,  7604, 17974, 12820, 18005]),
 np.int64(18597): array([ 2606, 12245,  9427,  5117, 16678, 17726]),
 np.int64(21257): array([  858, 16606,  7604, 13958,  3351, 14079]),
 np.int64(21488): array([16674, 14021, 12340,  3951, 15219,  1411]),
 np.int64(10768): array([ 8419, 10840,  1511,  5573,  7495,  2501]),
 np.int64(6501): array([ 1549,  4442, 17013,  1657, 13637,  5100]),
 np.int64(14451): array([12532,  1959,  1884, 12203,  8457, 16398]),
 np.int64(8652): array([ 1105, 16463, 18150,  7804,   324, 17536]),
 np.int64(4448): array([  858,  7551,  6041,   463, 10505,  6392]),
 np.int64(44925): array([ 7551, 18011,  1824, 15734,  5393, 10239]),
 np.int64(5672): array([ 1349, 16355,  7568, 16886, 15253,  7586]),
 np.int64(37556): array([ 7362, 13704, 15907, 15037,  5629,  4123]),
 np.int64(46148): array([ 7362,  4066, 14589, 10027, 13556, 12846]),
 np.int64(45171): array([ 4628, 13598, 10816, 15694,  5413,   989]),
 np.int64(16332): array([  263, 15049,  4549,  8786, 12026, 13487]),
 np.int64(1675): array([15269,  5390, 19452, 18827,  2066, 10367]),
 np.int64(134): array([18504,   113,  3488,   655, 11729,  6980]),
 np.int64(24597): array([18387, 15868, 14568, 17532,  2167, 17182]),
 np.int64(31694): array([13471, 10949, 14457, 15166,  7665,  9966]),
 np.int64(4493): array([4744, 5818, 7510, 2695, 7905,  482]),
 np.int64(11393): array([13164, 16767, 13031, 10574, 11477, 10710]),
 np.int64(31137): array([ 7362, 13481, 19156, 11692, 13627, 13844]),
 np.int64(4534): array([  475,  9830, 13010, 11350, 10524, 17233]),
 np.int64(21792): array([ 3805,  5838,  3159,  9346, 19717, 19470]),
 np.int64(1812): array([18762,  4442, 18380, 17037, 10439,  4870]),
 np.int64(5616): array([18504,  2237,  8479, 15852, 18711, 12454]),

In [62]:
item_frequency_sorted

       item  frequency
8168  16981        291
7574  15775        269
1560   3260        262
3141   6539        261
7947  16537        258
...     ...        ...
6071  12557          5
7446  15474          5
1025   2166          5
5600  11597          5
741    1571          5

[9535 rows x 2 columns]

In [36]:
lines = []
for user in all_users:
    top_items_str = ', '.join([str(item) for item in top_6_items_per_user[user]])
    negative_samples_str = ', '.join([str(item) for item in negative_samples_per_user[user]])
    # format the line as "user_id\ttop_items\tnegative_samples"
    line = f"{user}\t{top_items_str}\t{negative_samples_str}"
    lines.append(line)

tsv_file_path = '../user_items_negs.tsv'
with open(tsv_file_path, 'w') as file:
    file.write('\n'.join(lines))

In [37]:
from sklearn.model_selection import train_test_split

tsv_file_path = '../user_items_negs.tsv'
data = pd.read_csv(tsv_file_path, sep='\t', header=None, names=['user', 'items', 'negative_samples'])

users = data['user'].unique()

train_users, test_val_users = train_test_split(users, test_size=0.2, random_state=42)

val_users, test_users = train_test_split(test_val_users, test_size=0.5, random_state=42)

train_data = data[data['user'].isin(train_users)]
val_data = data[data['user'].isin(val_users)]
test_data = data[data['user'].isin(test_users)]

print(f"Training data size: {len(train_data)}")
print(f"Validation data size: {len(val_data)}")
print(f"Test data size: {len(test_data)}")

Training data size: 11458
Validation data size: 1432
Test data size: 1433

In [38]:
def save_to_tsv(df, file_path):
    df.to_csv(file_path, sep='\t', header=False, index=False)
    print(f"File saved to {file_path}")

# save the dataframes to TSV files
save_to_tsv(train_data, '../train.tsv')
save_to_tsv(val_data, '../val.tsv')
save_to_tsv(test_data, '../test.tsv')

File saved to train.tsv
File saved to val.tsv
File saved to test.tsv